[package]
name = "porc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.30.5"

[dev-dependencies]
pretty_assertions = "1.4.0"
unindent = "0.2.3"
